services:
  - type: web
    name: wb-finance
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn web.server:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
